Only set the capture if value is True (#244)
This only seems to affect the binary. If --capture-output is not set, it throws an error. Assume the value
might be set to None.

    $ ./ksm exec -- bash
    Imported config saved to profile App1 at keeper.ini.
    Error: Cannot execute command: __init__() got an unexpected keyword argument 'capture_output'

However if --capture-output is set it's happy as punch.

    $ KSM_DEBUG=DEBUG ./ksm exec --capture-output -- bash
    Imported config saved to profile App1 at keeper.ini.
    2022-03-25 16:02:14,911 | ksm | DEBUG | Setting public key id to the default: 10

So the change will only set the value if --capture-output is used.